/**
 * GitHub Actions Workflow Generator
 *
 * Generates workflow files for parallel Claude worker sessions.
 * Workers trigger on issue labeling and run Claude Code in headless mode.
 */

import * as fs from 'fs';
import * as path from 'path';
import { AutopilotConfig, DEFAULT_AUTOPILOT_CONFIG } from '../orchestrator/autopilot-config.js';

/**
 * Workflow generation options
 */
export interface WorkflowOptions {
  /** Workflow name */
  name?: string;
  /** Node.js version to use */
  nodeVersion?: string;
  /** Claude Code version (npm tag) */
  claudeVersion?: string;
  /** Additional environment variables */
  envVars?: Record<string, string>;
  /** Run tests before PR */
  runTests?: boolean;
  /** Run build before PR */
  runBuild?: boolean;
}

/**
 * Default workflow options
 */
export const DEFAULT_WORKFLOW_OPTIONS: Required<WorkflowOptions> = {
  name: 'Claude Worker',
  nodeVersion: '20',
  claudeVersion: 'latest',
  envVars: {},
  runTests: true,
  runBuild: true,
};

/**
 * Generate the Claude worker workflow YAML
 */
export function generateWorkerWorkflow(
  config: AutopilotConfig = DEFAULT_AUTOPILOT_CONFIG,
  options: WorkflowOptions = {}
): string {
  const opts = { ...DEFAULT_WORKFLOW_OPTIONS, ...options };
  const workerLabel = config.workerLabel || 'ready-for-claude';
  const timeout = parseTimeoutMinutes(config.workerTimeout);

  // Build environment variables section
  const envVars: Record<string, string> = {
    ANTHROPIC_API_KEY: '${{ secrets.ANTHROPIC_API_KEY }}',
    ...opts.envVars,
  };

  const envSection = Object.entries(envVars)
    .map(([key, value]) => `          ${key}: ${value}`)
    .join('\n');

  const workflow = `# Claude Worker - Parallel Development Session
# Generated by Workflow Pilot
# Triggers when issues are labeled with '${workerLabel}'

name: ${opts.name}

on:
  issues:
    types: [labeled]

jobs:
  claude-worker:
    # Only run when the specific label is added
    if: github.event.label.name == '${workerLabel}'

    runs-on: ubuntu-latest
    timeout-minutes: ${timeout}

    permissions:
      contents: write
      issues: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '${opts.nodeVersion}'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install Claude Code CLI
        run: npm install -g @anthropic-ai/claude-code@${opts.claudeVersion}

      - name: Extract issue context
        id: issue
        run: |
          echo "number=\${{ github.event.issue.number }}" >> $GITHUB_OUTPUT
          echo "title=\${{ github.event.issue.title }}" >> $GITHUB_OUTPUT

      - name: Create feature branch
        run: |
          BRANCH_NAME="claude-worker/issue-\${{ steps.issue.outputs.number }}"
          git config user.name "Claude Worker"
          git config user.email "claude-worker@github.actions"
          git checkout -b "$BRANCH_NAME"
          echo "branch=$BRANCH_NAME" >> $GITHUB_OUTPUT
        id: branch

      - name: Run Claude Code
        env:
${envSection}
        run: |
          # Extract issue body for context
          ISSUE_BODY=$(gh issue view \${{ steps.issue.outputs.number }} --json body -q .body)

          # Create prompt for Claude
          PROMPT="You are working on GitHub issue #\${{ steps.issue.outputs.number }}: \${{ steps.issue.outputs.title }}

Issue description:
$ISSUE_BODY

Instructions:
1. Implement the feature described in the issue
2. Follow the acceptance criteria listed
3. Write tests for new functionality
4. Keep changes focused on this issue only
5. Do not modify unrelated files

When done, summarize what you implemented."

          # Run Claude in non-interactive mode
          echo "$PROMPT" | claude --print --output-format stream-json 2>&1 | tee claude-output.log || true

      - name: Check for changes
        id: changes
        run: |
          if git diff --quiet && git diff --cached --quiet; then
            echo "has_changes=false" >> $GITHUB_OUTPUT
          else
            echo "has_changes=true" >> $GITHUB_OUTPUT
          fi
${opts.runTests ? `
      - name: Run tests
        if: steps.changes.outputs.has_changes == 'true'
        run: npm test
        continue-on-error: true
` : ''}${opts.runBuild ? `
      - name: Run build
        if: steps.changes.outputs.has_changes == 'true'
        run: npm run build
        continue-on-error: true
` : ''}
      - name: Commit changes
        if: steps.changes.outputs.has_changes == 'true'
        run: |
          git add -A
          git commit -m "feat: implement issue #\${{ steps.issue.outputs.number }}

\${{ steps.issue.outputs.title }}

Fixes #\${{ steps.issue.outputs.number }}

Co-Authored-By: Claude <noreply@anthropic.com>"

      - name: Push branch
        if: steps.changes.outputs.has_changes == 'true'
        run: git push -u origin \${{ steps.branch.outputs.branch }}

      - name: Create Pull Request
        if: steps.changes.outputs.has_changes == 'true'
        env:
          GH_TOKEN: \${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr create \\
            --title "feat: \${{ steps.issue.outputs.title }}" \\
            --body "## Summary

Implements #\${{ steps.issue.outputs.number }}

## Changes

See commit history for details.

## Test Plan

- [ ] Tests pass
- [ ] Build succeeds
- [ ] Manual verification

---

*Automated by Claude Worker*

Fixes #\${{ steps.issue.outputs.number }}" \\
            --base main \\
            --head \${{ steps.branch.outputs.branch }}

      - name: Comment on issue
        env:
          GH_TOKEN: \${{ secrets.GITHUB_TOKEN }}
        run: |
          if [ "\${{ steps.changes.outputs.has_changes }}" == "true" ]; then
            gh issue comment \${{ steps.issue.outputs.number }} --body "Claude Worker has created a PR for this issue. Please review the changes."
          else
            gh issue comment \${{ steps.issue.outputs.number }} --body "Claude Worker analyzed this issue but did not make any changes. Manual intervention may be required."
          fi

      - name: Remove worker label
        env:
          GH_TOKEN: \${{ secrets.GITHUB_TOKEN }}
        run: |
          gh issue edit \${{ steps.issue.outputs.number }} --remove-label "${workerLabel}"
`;

  return workflow;
}

/**
 * Parse timeout string to minutes
 */
function parseTimeoutMinutes(timeout: string): number {
  const match = timeout.match(/^(\d+)([mh])$/);
  if (!match) {
    return 30; // Default 30 minutes
  }

  const value = parseInt(match[1], 10);
  const unit = match[2];

  if (unit === 'h') {
    return value * 60;
  }
  return value;
}

/**
 * Generate workflow file path
 */
export function getWorkflowPath(
  projectDir: string = process.cwd(),
  filename: string = 'claude-worker.yml'
): string {
  return path.join(projectDir, '.github', 'workflows', filename);
}

/**
 * Save workflow to file system
 */
export function saveWorkerWorkflow(
  config: AutopilotConfig = DEFAULT_AUTOPILOT_CONFIG,
  options: WorkflowOptions = {},
  projectDir: string = process.cwd()
): { success: boolean; path: string; error?: string } {
  const workflowPath = getWorkflowPath(projectDir);
  const workflowDir = path.dirname(workflowPath);

  try {
    // Ensure .github/workflows directory exists
    if (!fs.existsSync(workflowDir)) {
      fs.mkdirSync(workflowDir, { recursive: true });
    }

    // Generate and write workflow
    const workflow = generateWorkerWorkflow(config, options);
    fs.writeFileSync(workflowPath, workflow, 'utf-8');

    return { success: true, path: workflowPath };
  } catch (error) {
    return {
      success: false,
      path: workflowPath,
      error: error instanceof Error ? error.message : 'Unknown error',
    };
  }
}

/**
 * Check if workflow already exists
 */
export function workflowExists(
  projectDir: string = process.cwd(),
  filename: string = 'claude-worker.yml'
): boolean {
  const workflowPath = getWorkflowPath(projectDir, filename);
  return fs.existsSync(workflowPath);
}

/**
 * Generate a minimal CI workflow for the project
 */
export function generateCIWorkflow(
  options: {
    name?: string;
    nodeVersion?: string;
    testCommand?: string;
    buildCommand?: string;
  } = {}
): string {
  const {
    name = 'CI',
    nodeVersion = '20',
    testCommand = 'npm test',
    buildCommand = 'npm run build',
  } = options;

  return `# Continuous Integration
# Generated by Workflow Pilot

name: ${name}

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '${nodeVersion}'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: ${testCommand}

      - name: Run build
        run: ${buildCommand}
`;
}

/**
 * Validate that required secrets are documented
 */
export function getRequiredSecrets(): Array<{
  name: string;
  description: string;
  required: boolean;
}> {
  return [
    {
      name: 'ANTHROPIC_API_KEY',
      description: 'API key for Claude Code authentication',
      required: true,
    },
    {
      name: 'GITHUB_TOKEN',
      description: 'Automatically provided by GitHub Actions',
      required: false,
    },
  ];
}

/**
 * Generate setup instructions for the workflow
 */
export function generateSetupInstructions(
  config: AutopilotConfig = DEFAULT_AUTOPILOT_CONFIG
): string {
  const secrets = getRequiredSecrets();
  const workerLabel = config.workerLabel || 'ready-for-claude';

  return `## Claude Worker Setup Instructions

### 1. Add Required Secrets

Go to your repository Settings > Secrets and variables > Actions, and add:

${secrets.filter(s => s.required).map(s => `- **${s.name}**: ${s.description}`).join('\n')}

### 2. Create the Worker Label

Create a label called \`${workerLabel}\` in your repository:
- Go to Issues > Labels > New label
- Name: \`${workerLabel}\`
- Description: "Ready for Claude worker processing"
- Color: Choose a distinctive color (e.g., #7C3AED purple)

### 3. Enable GitHub Actions

Ensure GitHub Actions is enabled for your repository:
- Go to Settings > Actions > General
- Select "Allow all actions and reusable workflows"

### 4. Test the Workflow

1. Create or select an issue
2. Add the \`${workerLabel}\` label
3. Watch the Actions tab for the workflow run
4. Review the created PR

### Troubleshooting

- **Workflow not triggering**: Check that the label name matches exactly
- **API errors**: Verify ANTHROPIC_API_KEY is set correctly
- **Permission errors**: Ensure workflow has write permissions
`;
}
